bytedance/fedlearner

- fedlearner/data_join/raw_data_partitioner.py
Co-authored-by: fangchenliaohui <fangchenliaohui@bytedance.com>
> fix the raw data partitioner (#158)

- web_console/README.md
- web_console/libs/k8s.js
- web_console/libs/kubernetes_client.js
- web_console/package-lock.json
- web_console/package.json
- web_console/tests/.eslintrc
- web_console/tests/fixtures/test.json
- web_console/tests/fixtures/test.yaml
- web_console/tests/libs/k8s.test.js
- web_console/tests/utils/yaml.test.js
- web_console/utils/index.js
- web_console/utils/yaml.js
implement Kubernetes client by testing with `minikube`
> feat(web_console): kubernetes client

- deploy/kubernetes_operator/cmd/apiserver/main.go
- deploy/kubernetes_operator/pkg/apiserver/handler/handler.go
Add ing/svc/dp/secret proxy support so that end user could config ing/ds through web portal.
> add ing/svc/dp/secret proxy support for web portal

- deploy/charts/fedlearner/charts/fedlearner-apiserver/values.yaml
- deploy/charts/fedlearner/charts/fedlearner-operator/values.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console/values.yaml
- deploy/charts/fedlearner/values.yaml
> update image tag

- fedlearner/proxy/channel.py
> add egress domain

- deploy/kubernetes_operator/pkg/operator/app_manager.go
- deploy/kubernetes_operator/pkg/operator/event_handler.go
Please take a look @DeliangFan
> fix: move invoke peer to grpc client

- example/privacy/label_protection/FL_Label_Protection_FMNIST_Demo.py
- example/privacy/label_protection/README.md
1. used autopep8 to format the code to conform to the PEP 8 style guide 
2. passed lint check.
> Label protection

- fedlearner/data_join/data_portal_job_manager.py
- fedlearner/data_join/data_portal_worker.py
- protocols/fedlearner/common/data_portal_service.proto
- test/data_join/test_data_portal_master.py
- test/data_join/test_data_portal_worker.py
1. the potential reuse the origin etcd meta data.
2.  use the full file path to split sub-map task
> Hot fix the bug for data portal

- deploy/charts/fedlearner-stack/charts/elastic-stack/charts/elasticsearch/values.yaml
- deploy/charts/fedlearner-stack/charts/elastic-stack/charts/filebeat/values.yaml
- deploy/charts/fedlearner-stack/charts/elastic-stack/charts/kibana/values.yaml
It only take several minutes to download these images rather than tens minutes.
> set the es-stack repository to aliyun

- deploy/charts/fedlearner-add-on/server-snippet.txt
- deploy/charts/fedlearner-add-on/values.yaml
Optimize fedleaner add on to make it simpler.
helm install fedlearner-add-on ./fedlearner-add-on \
--set imageCredentials.registry=xxxx \
--set imageCredentials.username=xxxx \
--set imageCredentials.password=xxxx \
--set service.externalName=xxxx
> optimize fedlearner-add-on

- deploy/scripts/data_join/run_data_join_master.sh
- fedlearner/data_join/cmd/data_join_master_service.py
- fedlearner/data_join/data_join_master.py
- fedlearner/data_join/data_join_worker.py
- fedlearner/data_join/raw_data_manifest_manager.py
- fedlearner/data_join/routine_worker.py
- protocols/fedlearner/common/data_join_service.proto
- test/data_join/test_data_join_worker.py
batch mode meaning determine the raw at when master launched, and the worker will exit when all partition of data-join finished
> make the data-join support batch mode.

- fedlearner/data_join/joiner_impl/stream_joiner.py
- fedlearner/data_join/routine_worker.py
> add more debug info for routine worker and bug-fix for the stream_joiner for the concern case

- web_console/api/federation.js
- web_console/components/JobCommonInfo.jsx
- web_console/components/ServerTicketSelect.jsx
- web_console/libs/http.js
- web_console/package-lock.json
- web_console/package.json
- web_console/pages/job/[id].jsx
- web_console/pages/raw_data/[id].jsx
- web_console/rpc/meta.proto
- web_console/rpc/server.js
- web_console/tests/api/federation.test.js
- **feat**: support `job_type` and `role` filter on `/api/v1/federations/:id/tickets` api
- **feat**: support pass options to `fetcher`
- **chore**: `getTickets` rpc method return `public_params` instead of `params`
- **fix**: no condition of `useSWR` usage which cause no-use requests
> feat(web_console): support filter on federation tickets

- deploy/scripts/trainer/run_trainer_worker.sh
[Add]add env MODEL_NAME for model serving
> [Add]add env MODEL_NAME for model serving

- deploy/charts/fedlearner/charts/fedlearner-web-console/values.yaml
- deploy/scripts/aliyun/install.sh
1. enable create oss bucket in aliyun
2. add some envs
> add oss and env

- web_console/components/Form.jsx
- web_console/constants/form-default.js
- web_console/pages/admin/federation.jsx
* fix federation doesn't check form type on submitting
* fix federation doesn't parse env
> fix(web_console): remove volumes and volumeMounts in federation

- web_console/components/Form.jsx
- web_console/constants/form-default.js
- web_console/pages/admin/federation.jsx
* feature: support fill json value with array
* fix: default field name of env
> fix(web_console): federation form

- fedlearner/data_join/cmd/generate_csv_raw_data.py
- fedlearner/data_join/cmd/rsa_psi_preprocessor_cli.py
- fedlearner/data_join/common.py
- fedlearner/data_join/csv_dict_writer.py
- fedlearner/data_join/data_block_dumper.py
- fedlearner/data_join/data_block_manager.py
- fedlearner/data_join/example_id_batch_fetcher.py
- fedlearner/data_join/example_id_visitor.py
- fedlearner/data_join/example_validate_impl/__init__.py
- fedlearner/data_join/item_batch_seq_processor.py
- fedlearner/data_join/joiner_impl/__init__.py
- fedlearner/data_join/output_writer_impl/__init__.py
- fedlearner/data_join/raw_data_iter_impl/__init__.py
- fedlearner/data_join/raw_data_iter_impl/csv_dict_iter.py
- fedlearner/data_join/raw_data_iter_impl/tf_record_iter.py
- fedlearner/data_join/raw_data_partitioner.py
- fedlearner/data_join/raw_data_visitor.py
- fedlearner/data_join/rsa_psi/rsa_psi_component.py
- fedlearner/data_join/rsa_psi/rsa_psi_preprocessor.py
- fedlearner/data_join/transmit_leader.py
- fedlearner/data_join/visitor.py
- test/data_join/test_rsa_psi.py
Reverts bytedance/fedlearner#311
> Revert "not use the csv dict reader/writer since the schema cost too much memory"

- fedlearner/common/metrics.py
- web_console/utils/job_builder.js
This reverts commit 69bd5c3f346c3794928facc50cf3e0e0b4c85e3e.
> Revert "Turn off es metrics by default (#334)"

- web_console/components/CommonTicket.jsx
- web_console/pages/admin/federation.jsx
* ticket raw data name
* form data not updated when editing ticket
* federation form checker
> fix: v1.5 bugs

- example/privacy/label_protection/README.md
update readme and technical report
> update readme and technical report

- web_console/pages/raw_data/index.jsx
* fix image lost when switching form type
> feat: rawdata env:

- docs/tutorials/quick_start.md
- example/mnist/follower.py
- example/mnist/leader.py
- example/mnist/test.sh
fix #402
Modify the example mnist to make it meet the new usage requirements of "_get_features_and_labels_from_input_fn" and update docs
> Fix issues 402 update example mnist

- web_console_v2/api/fedlearner_webconsole/project/add_on.py
- web_console_v2/api/fedlearner_webconsole/project/apis.py
- web_console_v2/api/fedlearner_webconsole/project/models.py
- web_console_v2/api/fedlearner_webconsole/rpc/client.py
- web_console_v2/api/protocols/fedlearner_webconsole/proto/common.proto
- web_console_v2/api/protocols/fedlearner_webconsole/proto/project.proto
- web_console_v2/api/test/fedlearner_webconsole/db_test.py
- web_console_v2/api/test/fedlearner_webconsole/project/add_on_test.py
- web_console_v2/api/test/fedlearner_webconsole/project/apis_test.py
- web_console_v2/api/test/fedlearner_webconsole/rpc/client_test.py
1. Refactor the type of participant in protobuf `Project` from `map<string, Participant>` to `repeated Participant`.
> [WebConsoleV2] Refactor participant from map to list

- web_console_v2/api/fedlearner_webconsole/auth/apis.py
Frontend need user id when users log in.
> Fix: return user id

- web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
- web_console_v2/api/test/fedlearner_webconsole/workflow_template/apis_test.py
* Removes checks in post API, only checks required fields.
* Makes list API work with group_alias filter instead of workflow id.
> [WebConsoleV2] Refines workflow template API.

- web_console_v2/api/fedlearner_webconsole/rpc/client.py
- web_console_v2/api/fedlearner_webconsole/rpc/server.py
- web_console_v2/api/fedlearner_webconsole/workflow/apis.py
- web_console_v2/api/protocols/fedlearner_webconsole/proto/service.proto
- web_console_v2/api/test/scheduler_test.py
To help users look up peer config when PUT workflow and FORK workflow, making GET api able to get peer workflows' config.
> [WebConsoleV2] make workflow GET api able to get peer workflow

- web_console_v2/api/config.py
- web_console_v2/api/run_prod.sh
db should be upgrade before server starts.
> [WebConsoleV2] Fixes prod issue

- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/cluster_role.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/cluster_role_binding.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/values.yaml
K8s client inclusterconfig needs permission.
Refer to: https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py
> [WebConsoleV2]: Fix web-console-v2 permission

- web_console_v2/api/fedlearner_webconsole/dataset/models.py
- web_console_v2/api/fedlearner_webconsole/db.py
- web_console_v2/api/fedlearner_webconsole/project/models.py
- web_console_v2/api/fedlearner_webconsole/utils/file_manager.py
- web_console_v2/api/protocols/fedlearner_webconsole/proto/dataset.proto
- web_console_v2/api/test/fedlearner_webconsole/db_test.py
- web_console_v2/api/test/fedlearner_webconsole/utils/file_manager_test.py
- web_console_v2/api/testing/fake_file_manager.py
1. Dataset model
2. Fix none in project model
3. Add a few methods that will be used in FileManager
> [WebConsoleV2] Dataset Model

- web_console_v2/api/fedlearner_webconsole/project/apis.py
- web_console_v2/api/test/fedlearner_webconsole/project/apis_test.py
Number of workflow is shown on UI when listing project.
> [WebConsoleV2] Add workflow num in list project

- web_console_v2/api/config.py
- web_console_v2/api/requirements.txt
> [WebConsoleV2] Makes DB configurable.

- web_console_v2/api/README.md
- web_console_v2/api/manage.py
- web_console_v2/api/run_prod.sh
- web_console_v2/run_prod.sh
In some cases, we don't need to migrate the DB automatically, for example, some distributed systems.
> [WebConsoleV2] Makes DB migration as an option.

- web_console/api/job.js
- web_console/components/CommonJobList.jsx
- web_console/pages/training/job/index.jsx
- jobs 接口添加分页
- jobs 接口去除部分冗余信息 (k8s_meta_snapshot)
- jobs 接口添加关键词/job_type筛选
> fix(webconsole_v1): implement pagination & type & keyword filters for job list query

- web_console_v2/client/src/components/PrintLogs/index.tsx
- web_console_v2/client/src/views/LogsViewer/JobLogs/index.tsx
- web_console_v2/client/src/views/LogsViewer/PodLogs/index.tsx
- web_console_v2/client/src/views/LogsViewer/index.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/JobExecutionDetailsDrawer.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/JobExecutionLogs.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/JobExecutionPODs.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/index.tsx
- Now you can view the Peer side's job details
> [WebConsoleV2] Introduce PrintLogs component unify the way display logs

- web_console_v2/client/package-lock.json
- web_console_v2/client/package.json
- web_console_v2/client/src/components/WorkflowJobsFlowChart/index.tsx
- web_console_v2/client/src/hooks/index.ts
- web_console_v2/client/src/typings/global.d.ts
- web_console_v2/client/src/views/Workflows/CreateWorkflow/SteptTwoConfig/index.tsx
- web_console_v2/client/tsconfig.json
- Provide a fitView button that allows the user to fit anytime
- Auto fitView after chart resize
- Open Global config drawer initially if has during workflow create progress
> [WebConsoleV2] Workflow flow chart now support fitView

- web_console_v2/client/src/components/PrintLogs/index.tsx
- web_console_v2/client/src/components/WorkflowJobsFlowChart/index.tsx
- web_console_v2/client/src/i18n/resources/modules/workflow.ts
- web_console_v2/client/src/services/mocks/v2/jobs/All-completed-Initiative/log.ts
- web_console_v2/client/src/services/mocks/v2/workflows/examples.ts
- web_console_v2/client/src/styles/animations.ts
- web_console_v2/client/src/typings/job.ts
- web_console_v2/client/src/views/LogsViewer/JobLogs/index.tsx
- web_console_v2/client/src/views/LogsViewer/PodLogs/index.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/JobExecutionPODs.tsx
If the user not at the bottom of the printer, meanwhile, new logs have been fetched, show him a scroll-to-bottom button
> [WebConsoleV2] PrintLogs add scroll to bottom function if has new logs

- web_console_v2/api/README.md
- web_console_v2/api/command.py
- web_console_v2/api/config.py
- web_console_v2/api/fedlearner_webconsole/app.py
- web_console_v2/api/run_dev.sh
- web_console_v2/api/server.py
Separates the configs of command app and prod app.
> [WebConsoleV2] Fixes the scheduler starting issue.

- example/mnist/leader.py
- example/mnist/test.sh
- fedlearner/trainer/trainer_master_client.py
- fedlearner/trainer/trainer_worker.py
Support multiple training epochs in LocalTrainerMasterClient.
> support multiple training epochs in LocalTrainerMasterClient

- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/ingress.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/values.yaml
Example:
helm template fedlearner-web-console-v2 \
--set "ingress.hosts[0].domainName=fl-xxx.com" \
--set "ingress.tls[0].domainNames={fl-xxx.com}"
> [WebConsoleV2] fix helm chart

- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/deployment.yaml
- web_console_v2/Dockerfile
- web_console_v2/run_prod.sh
kubectl port-forward fedlearner-web-consolve-v2-xxxx-xxxxx 1992:1992
> [WebConsoleV2] dockerfile support vscode

- web_console_v2/client/src/components/BreadcrumbLink/index.tsx
- web_console_v2/client/src/components/PrintLogs/index.tsx
- web_console_v2/client/src/components/WorkflowJobsFlowChart/types.ts
- web_console_v2/client/src/i18n/resources/modules/workflow.ts
- web_console_v2/client/src/services/mocks/v2/workflows/:id/index.ts
- web_console_v2/client/src/services/mocks/v2/workflows/examples.ts
- web_console_v2/client/src/services/mocks/v2/workflows/index.ts
- web_console_v2/client/src/shared/workflow.test.ts
- web_console_v2/client/src/shared/workflow.ts
- web_console_v2/client/src/styles/_theme.ts
- web_console_v2/client/src/styles/_variables.css
- web_console_v2/client/src/styles/variables.less
- web_console_v2/client/src/typings/job.ts
- web_console_v2/client/src/typings/workflow.ts
- web_console_v2/client/src/views/Workflows/CreateWorkflow/StepOneBasic/index.tsx
- web_console_v2/client/src/views/Workflows/CreateWorkflow/SteptTwoConfig/index.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/JobExecutionDetailsDrawer.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/JobExecutionLogs.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/JobExecutionPODs.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/index.tsx
- web_console_v2/client/src/views/Workflows/WorkflowList/index.tsx
- Remove strict rules for workflow name during create
- Add spinner for peer side workflow chart
- Reveal pod conditions message when pod pending or failed
- Display K8s job name inside job exe drawer
> [WebConsoleV2] Add UUID for workflow

- deploy/scripts/data_portal/run_data_portal_worker.sh
- fedlearner/common/common.py
- fedlearner/common/metrics.py
- fedlearner/data_join/cmd/data_portal_worker_cli.py
- fedlearner/data_join/common.py
- fedlearner/data_join/data_block_manager.py
- fedlearner/data_join/example_id_dumper.py
- fedlearner/data_join/joiner_impl/optional_stats.py
- fedlearner/data_join/joiner_impl/stream_joiner.py
- fedlearner/data_join/raw_data_iter_impl/metric_stats.py
- protocols/fedlearner/common/data_join_service.proto
- requirements.txt
- test/data_join/test_data_portal_worker.py
multi indices to resolve ES storage overflow. Currently we can emit up to 1 billion documents to ES with no more than 70GB disk usage.
> multi indices

- example/wide_n_deep/follower.py
- example/wide_n_deep/leader.py
- example/wide_n_deep/make_data.py
- example/wide_n_deep/test.sh
- fedlearner/trainer/estimator.py
> fix: repeated checkpoint in trainer

- web_console_v2/api/requirements.txt
fixed package version of webconsole v2 requirements.txt
> [WebconsoleV2]: fixed requirements package version

- web_console_v2/api/fedlearner_webconsole/app.py
- web_console_v2/api/fedlearner_webconsole/envs.py
- web_console_v2/api/fedlearner_webconsole/utils/file_manager.py
- web_console_v2/api/requirements.txt
- web_console_v2/api/test/fedlearner_webconsole/utils/file_manager_test.py
> [WebConsoleV2]: use pyarrow client as hdfs-tools

- web_console_v2/client/package-lock.json
- web_console_v2/client/package.json
- web_console_v2/client/src/components/ReadFile/index.tsx
- Fix problem oif File upload failed
> [WebConsoleV2] Bump antd to 4.14.0

- web_console_v2/api/Makefile
> [WebConsoleV2]: add test to flask_cli

- web_console_v2/client/src/i18n/resources/modules/workflow.ts
- web_console_v2/client/src/styles/antd-overrides.less
- web_console_v2/client/src/views/WorkflowTemplates/TemplateForm/StepTwoJobs/JobComposeDrawer/index.tsx
- web_console_v2/client/src/views/WorkflowTemplates/TemplateForm/StepTwoJobs/index.tsx
- web_console_v2/client/src/views/WorkflowTemplates/TemplateForm/store.ts
- Fix job definition values lost when click submit
> [WebConsoleV2]: Implement Job delete on template editing

- web_console_v2/client/scripts/lessVarsTransform.js
- web_console_v2/client/src/libs/request.ts
- web_console_v2/client/src/services/mocks/v2/auth/signin.ts
- web_console_v2/client/src/services/workflow.ts
- web_console_v2/client/src/stores/workflow.ts
- web_console_v2/client/src/styles/_theme.ts
- web_console_v2/client/src/styles/antd-overrides.less
- web_console_v2/client/src/styles/variables.less
- web_console_v2/client/src/typings/job.ts
- web_console_v2/client/src/typings/workflow.ts
- web_console_v2/client/src/views/WorkflowTemplates/TemplateForm/StepTwoJobs/index.tsx
- web_console_v2/client/src/views/WorkflowTemplates/TemplateList/index.tsx
- web_console_v2/client/src/views/Workflows/ForkWorkflow/StepTwoConfig/index.tsx
- web_console_v2/client/src/views/Workflows/WorkflowDetail/index.tsx
- Change CreateJobFlag to proto enum
> [WebConsoleV2] Template download & Fix Job values lost due to form reset

- web_console_v2/api/fedlearner_webconsole/exceptions.py
- web_console_v2/api/fedlearner_webconsole/project/apis.py
- web_console_v2/api/fedlearner_webconsole/rpc/client.py
- web_console_v2/api/fedlearner_webconsole/utils/decorators.py
- web_console_v2/api/test/fedlearner_webconsole/rpc/client_test.py
- web_console_v2/api/test/fedlearner_webconsole/utils/decorators_test.py
> [WebConsoleV2]: retry with grpc

- deploy/scripts/trainer/run_tree_worker.sh
- fedlearner/model/tree/packing.py
- fedlearner/model/tree/trainer.py
- fedlearner/model/tree/tree.py
- test/tree_model/test_pack.py
> pack_grad_hess

- web_console_v2/api/fedlearner_webconsole/utils/es.py
- web_console_v2/api/fedlearner_webconsole/workflow_template/apis.py
- web_console_v2/api/test/fedlearner_webconsole/workflow_template/apis_test.py
- web_console_v2/client/src/i18n/resources/modules/dataset.ts
- web_console_v2/client/src/i18n/resources/modules/workflow.ts
- web_console_v2/client/src/shared/file.ts
- web_console_v2/client/src/shared/queryClient.ts
- web_console_v2/client/src/views/Datasets/CreateDataset/index.tsx
- web_console_v2/client/src/views/WorkflowTemplates/TemplateList/TemplateUploadDialog.tsx
- web_console_v2/client/src/views/WorkflowTemplates/TemplateList/index.tsx
- web_console_v2/client/src/views/WorkflowTemplates/index.tsx
commit 20bed1401843a56ff777678d235048aa2f551e85
Merge branch 'add_config_for_post_put' of code.byted.org:data/fedlearner_web_console_v2 into add_config_for_post_put
commit 042b8cb2c5869f5b74298f434df2163fa4d55d87
fix no config for post and put
commit b54aa1f506299b6b76ec38cc79f1ea2f176af0a5
add create tables
commit 3ad2bc529f0b5d00f9027233aa6e8ffe568691cf
feat(tpl): support upload template.json on list page
commit a202822f9db4319455fb20eb8da527a4f5697ff0
Escapes new lines when using curl.
> [WebConsole] Sync to github.

- fedlearner/model/tree/tree.py
> feat(tree_metrics): add iter_metrics_handler

- fedlearner/data_join/data_portal_job_manager.py
- test/data_join/test_data_portal_job_manager.py
> feat(data-join): support ignoring files starting with .

- fedlearner/common/mysql_client.py
Creates table datasourcemeta if it does not exist, otherwise the worker which uses MySQLClient will crash.
> fix(mysql_client): creates table if datasourcemeta does not exist

- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/public_service.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/values.yaml
> feat(deploy): adds node port service for web console v2

- deploy/charts/fedlearner/values.yaml
* Enables webconsole v2
* Disables webconsole v1.5
> feat(deploy): enables webconsole v2 by default

- sgx/docker/fedlearner-sgx-dev.dockerfile
- sgx/docker/tf/grpc.diff
Change the TlsChannelSecurityConnector::check_peer Function.
> Add grpc sgx-ra-tls C++ example

- deploy/charts/fedlearner-stack/charts/sparkoperator/README.md
- deploy/charts/fedlearner-stack/charts/sparkoperator/ci/test-values.yaml
- deploy/charts/fedlearner-stack/charts/sparkoperator/templates/crd-cleanup-job.yaml
- deploy/charts/fedlearner-stack/charts/sparkoperator/templates/spark-operator-deployment.yaml
- deploy/charts/fedlearner-stack/charts/sparkoperator/templates/webhook-cleanup-job.yaml
- deploy/charts/fedlearner-stack/charts/sparkoperator/templates/webhook-init-job.yaml
- deploy/charts/fedlearner-stack/charts/sparkoperator/templates/webhook-service.yaml
- deploy/charts/fedlearner-stack/charts/sparkoperator/values.yaml
- deploy/charts/fedlearner-stack/values.yaml
修改 sparkoperator 的 charts 和其他的的 image 的格式保持统一。
[TESTED]
dry-run
> chore(deploy): refactor image structure

- Dockerfile
- deploy/scripts/data_join/run_data_join_leader_master.sh
- deploy/scripts/data_join/run_data_join_master.sh
- deploy/scripts/data_join/run_data_join_worker.sh
- deploy/scripts/data_join/run_psi_data_join_follower_worker.sh
- deploy/scripts/data_join/run_psi_data_join_follower_worker_v2.sh
- deploy/scripts/data_join/run_psi_data_join_leader_worker.sh
- deploy/scripts/data_join/run_psi_data_join_leader_worker_v2.sh
- deploy/scripts/data_portal/run_data_portal_master.sh
- deploy/scripts/data_portal/run_data_portal_worker.sh
- deploy/scripts/pre_start_hook.sh
- deploy/scripts/trainer/run_merge_scores.sh
- deploy/scripts/trainer/run_trainer_master.sh
- deploy/scripts/trainer/run_trainer_ps.sh
- deploy/scripts/trainer/run_trainer_worker.sh
- deploy/scripts/trainer/run_tree_worker.sh
- fedlearner/common/hooks.py
- test/common/for_test_hooks.py
- test/common/test_hooks.py
- 增加 PRE_START_HOOK 的环境变量的支持，每次任务执行前都会执行 PRE_START_HOOK 的脚本
- 增加了 kerberos client 的依赖
[TESTED]
> feat(scripts): add pre_start_hook

- Dockerfile
> fix(imags): fix krb5 installation

- Dockerfile
> chore(images): add cron

- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/ingress-v1beta1.yaml
k8s 1.16 - 1.18 使用 ing.v1beta1.networking.k8s.io
k8s 1.19+ 使用 ing.v1.networking.k8s.io
> fix(deploy): use v1beta1 for 1.16-1.18 and v1 for 1.19+

- sgx/gramine/CI-Examples/wide_n_deep/test-ps-sgx.sh
fix leader or follower boot error
> fix(script): add sleep to start script

- fedlearner/model/tree/loss.py
> feat(tree): enable confusion matrix

- deploy/charts/fedlearner-add-on/templates/ingress-v1.yaml
- deploy/charts/fedlearner-add-on/templates/ingress-v1beta1.yaml
- deploy/charts/fedlearner-add-on/values.yaml
- deploy/charts/fedlearner/charts/fedlearner-operator/templates/ingress-v1.yaml
- deploy/charts/fedlearner/charts/fedlearner-operator/templates/ingress-v1beta1.yaml
- deploy/charts/fedlearner/charts/fedlearner-operator/values.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/ingress-v1.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/templates/ingress-v1beta1.yaml
- deploy/charts/fedlearner/charts/fedlearner-web-console-v2/values.yaml
使用新的网络拓扑模式，保证公网上的 tls sni 国家备案过。
> feat(deploy): add new networking topology

- deploy/kubernetes_operator/pkg/operator/pod.go
- deploy/kubernetes_operator/pkg/operator/service.go
- deploy/kubernetes_operator/pkg/operator/util.go
support multi port in service and overwrite container port to 0 when pod use host network.
> feat(operator): support multi port in service and overwrite container port to 0

- deploy/scripts/data_join/run_data_join_master.sh
- deploy/scripts/data_join/run_data_join_worker.sh
- deploy/scripts/rsa_psi/run_rsa_psi_signer.sh
- deploy/scripts/trainer/run_fedavg.sh
- deploy/scripts/trainer/run_trainer_master.sh
- deploy/scripts/trainer/run_trainer_ps.sh
- deploy/scripts/trainer/run_trainer_worker.sh
- deploy/scripts/trainer/run_tree_worker.sh
- fedlearner/trainer/cluster_server.py
- fedlearner/trainer/trainer_master.py
- fedlearner/trainer/trainer_worker.py
适配站内网络环境，通过环境变量控制grpc server的listen port。
> chore(nn): adapt to hostnetwork

- fedlearner/model/tree/loss.py
feat(tree): enable top metrics, including top 10% and top 20% recall, precise, diff
> feat(tree): enable top metrics

- fedlearner/common/metric_collector.py
- fedlearner/common/metrics.py
- fedlearner/model/tree/loss.py
- fedlearner/model/tree/tree.py
- requirements.txt
1. Add a new metric collector based on opentelemetry
2. Support metrics collection during tree model training
> feat(metrics): add metric collector and support tree model training

- fedlearner/common/metric_collector.py
1. using a more generic cluster name env
2. fix custom service label
> fix(metrics): fix cluster name env

- deploy/scripts/trainer/run_tree_worker.sh
- example/tree_model/test.sh
- fedlearner/model/tree/trainer.py
- test/tree_model/test_filter_files.py
cherry pick from https://github.com/bytedance/fedlearner/commit/578a3ea9bba594695c38626473b6430bbd4550cf at master branch.
> feat(tree): add file_wildcard to filter files (#981)

- deploy/scripts/trainer/run_trainer_master.sh
- fedlearner/trainer/trainer_master.py
- fedlearner/trainer/trainer_worker.py
增加export_model，用于控制是否export模型，在train的mode下，默认发布，在其余mode下，检查export_model字段
> chore(trainer): export model for eval mode

- deploy/scripts/trainer/run_trainer_master.sh
- fedlearner/trainer/data_visitor.py
- fedlearner/trainer/trainer_worker.py
> feat(nn): add data path to start scripts

- fedlearner/data_join/sort_run_dumper.py
fix logic bug when fpath is none
> fix(data_join): hot-fix fpath is none

- deploy/scripts/env_to_args.sh
> fix(deploy): solve pull code startswith file error

- fedlearner/trainer/data_visitor.py
Co-authored-by: 杭卫强 <hangweiqiang@bytedance.com>
> refactor(visitor): change allocate logic of DataPathVisitor (#1029)

- fedlearner/model/crypto/secret_sharing.py
- test/tree_model/test_secret_sharing.py
> feat(tree): add secret sharing multiplication

- example/tree_model/merge_scores.py
- fedlearner/model/tree/trainer.py
- fedlearner/model/tree/trainer_master_client.py
- fedlearner/model/tree/utils.py
- test/tree_model/test_trainer.py
在DataBlockLoader类以及LocalTrainerMasterClient类中支持file_wildcard参数，树模型在eval模式下会使用DataBlockLoader读取数据。
> feat(tree): add file_wildcard to DataBlockLoader

- fedlearner/channel/client_interceptor.py
- fedlearner/model/tree/tree.py
- fedlearner/trainer/bridge.py
- fedlearner/trainer/run_hooks.py
- fedlearner/trainer/trainer_master.py
apply metric collector to nn model, including train and eval mode
> feat(metrics): apply new metrics to nn model

- fedlearner/channel/client_interceptor.py
- fedlearner/model/tree/tree.py
- fedlearner/trainer/bridge.py
- fedlearner/trainer/run_hooks.py
- fedlearner/trainer/trainer_master.py
pick from master
ref: https://github.com/bytedance/fedlearner/pull/1031
> feat(metrics): apply new metrics to nn model (#1031)

- example/tree_model/test.sh
- fedlearner/model/tree/trainer.py
- test/tree_model/test_trainer.py
> feat(tree): add multiprocessing tree data loader (#1041)

- fedlearner/channel/channel.py
- fedlearner/channel/client_interceptor.py
- fedlearner/common/metric_collector.py
- fedlearner/trainer/bridge.py
- fedlearner/trainer/parameter_server.py
- fedlearner/trainer/run_hooks.py
- fedlearner/trainer/trainer_master.py
- fedlearner/trainer/trainer_worker.py
1. metric collector lib support global tags
2. append more metrics to nn model
> feat(metrics): append more metrics to nn model

- deploy/scripts/env_to_args.sh
> fix(deploy): solve pull code startswith file error (#1020)

- deploy/scripts/env_to_args.sh
修复pull_code中pure_path缺少$不能解析参数的问题
> fix(deploy): fix pure path error

- deploy/scripts/trainer/run_trainer_master.sh
- fedlearner/trainer/data_visitor.py
修复DataPathVisitor，因为data_block不包含event_time和start_time
> fix(trainer): fix data path visitor

- fedlearner/trainer/trainer_master.py
支持在eval mode下添加checkpoints的hook
> refactor(trainer): add checkpoint hooks for eval

- .github/workflows/ci.yaml
- fedlearner/trainer/trainer_master.py
* feat(trainer): save checkpoints when load no data
* feat(trainer): save checkpoints when load no data
* feat(trainer): save checkpoints when load no data
* feat(trainer): save checkpoints when load no data
> feat(trainer): save checkpoints when load no data (#1066)

- fedlearner/fedavg/fedavg.py
- fedlearner/fedavg/master.py
Support metrics collection during nn horizontal model training
> feat(metrics): support fedavg training

- fedlearner/trainer/data_visitor.py
- fedlearner/trainer/trainer_worker.py
- fedlearner/trainer/utils.py
支持通过start_date，end_date过滤DataPathVisitor数据集
> feat(trainer): data_path_visitor add date filter
